# -*- coding: utf-8 -*-
"""
Created on Wed Feb  5 20:00:57 2020

@author: David
"""

for i in range(1, 1):
    print("The value of i is currently", i) # Note: if the set generated by 
                                            # the range() function is empty, 
                                            # the loop won't execute its body at all.
    